#!/bin/bash
#
#
# This software is Copyright (c) Robert Koliha, 2001-2002.
# Robert Koliha grants you the rights to distribute and use
# this software as governed by the terms of the GNU General
# Public License.
#
# http://www.gnu.org/copyleft/gpl.html

#
# This script grabs all of the modem/cpe ip's connected to your network for
# the iplogger.
# reccomended that this be run hourly
#

# read config file
. /etc/isgtools.sh

cd $iplogpath
./ip-grab
