#!/bin/bash
#
#
# This software is Copyright (c) Robert Koliha, 2001-2002.
# Robert Koliha grants you the rights to distribute and use
# this software as governed by the terms of the GNU General
# Public License.
#
# http://www.gnu.org/copyleft/gpl.html

#
# NOTE: this is referenced by the modemsearch/cmsearch scripts for pulling
#       live CPE information from the uBR
#


# read config file
. /etc/isgtools.sh

# SSTRING is used for referencing already created files
# basically the second value passed is the macid and it pastes the ubr commands
# and the interface / sid to search for into the variable $searchstring
SSTRING=$2
searchstring=$(echo "sh int $intid mod 0 | i $tsid")

# sub creation
ubr1() {
(echo "$ubruser";echo "$ubrpass" ; echo "$searchstring" ;echo exit) | nc -n $ubr1ip 23 | grep -v ">" | grep -v ÿ | grep -v User | grep -v Pass  | grep -v "+" > ubr-info.$SSTRING
(echo $UBR) > ubrnum.$SSTRING
echo 1 > ubrnum.clear.$SSTRING
}
ubr2() {
(echo "$ubruser";echo "$ubrpass" ; echo "$searchstring" ;echo exit) | nc -n $ubr2ip 23 | grep -v ">" | grep -v ÿ | grep -v User | grep -v Pass  | grep -v "+"  > ubr-info.$SSTRING
(echo $UBR) > ubrnum.$SSTRING
echo 2 > ubrnum.clear.$SSTRING
}
ubr3() {
(echo "$ubruser";echo "$ubrpass" ; echo "$searchstring" ;echo exit) | nc -n $ubr3ip 23 | grep -v ">" | grep -v ÿ | grep -v User | grep -v Pass  | grep -v "+" > ubr-info.$SSTRING
(echo $UBR) > ubrnum.$SSTRING
echo 3 > ubrnum.clear.$SSTRING
}
ubr4() {
(echo "$ubruser";echo "$ubrpass" ; echo "$searchstring" ;echo exit) | nc -n $ubr4ip 23 | grep -v ">" | grep -v ÿ | grep -v User | grep -v Pass  | grep -v "+" > ubr-info.$SSTRING
(echo $UBR) > ubrnum.$SSTRING
echo 4 > ubrnum.clear.$SSTRING
}
ubr5() {
(echo "$ubruser";echo "$ubrpass" ; echo "$searchstring" ;echo exit) | nc -n $ubr5ip 23 | grep -v ">" | grep -v ÿ | grep -v User | grep -v Pass  | grep -v "+" > ubr-info.$SSTRING
(echo $UBR) > ubrnum.$SSTRING
echo 5 > ubrnum.clear.$SSTRING
}
ubr6() {
(echo "$ubruser";echo "$ubrpass" ; echo "$searchstring" ;echo exit) | nc -n $ubr6ip 23 | grep -v ">" | grep -v ÿ | grep -v User | grep -v Pass  | grep -v "+" > ubr-info.$SSTRING
(echo $UBR) > ubrnum.$SSTRING
echo 6 > ubrnum.clear.$SSTRING
}
ubr7() {
(echo "$ubruser";echo "$ubrpass" ; echo "$searchstring" ;echo exit) | nc -n $ubr7ip 23 | grep -v ">" | grep -v ÿ | grep -v User | grep -v Pass  | grep -v "+" > ubr-info.$SSTRING
(echo $UBR) > ubrnum.$SSTRING
echo 7 > ubrnum.clear.$SSTRING
}
ubr8() {
(echo "$ubruser";echo "$ubrpass" ; echo "$searchstring" ;echo exit) | nc -n $ubr8ip 23 | grep -v ">" | grep -v ÿ | grep -v User | grep -v Pass  | grep -v "+" > ubr-info.$SSTRING
(echo $UBR) > ubrnum.$SSTRING
echo 8 > ubrnum.clear.$SSTRING
}
ubr9() {
(echo "$ubruser";echo "$ubrpass" ; echo "$searchstring" ;echo exit) | nc -n $ubr9ip 23 | grep -v ">" | grep -v ÿ | grep -v User | grep -v Pass  | grep -v "+" > ubr-info.$SSTRING
(echo $UBR) > ubrnum.$SSTRING
echo 9 > ubrnum.clear.$SSTRING
}
ubr10() {
(echo "$ubruser";echo "$ubrpass" ; echo "$searchstring" ;echo exit) | nc -n $ubr10ip 23 | grep -v ">" | grep -v ÿ | grep -v User | grep -v Pass  | grep -v "+" > ubr-info.$SSTRING
(echo $UBR) > ubrnum.$SSTRING
echo 10 > ubrnum.clear.$SSTRING
}
ubr11() {
(echo "$ubruser";echo "$ubrpass" ; echo "$searchstring" ;echo exit) | nc -n $ubr11ip 23 | grep -v ">" | grep -v ÿ | grep -v User | grep -v Pass  | grep -v "+" > ubr-info.$SSTRING
(echo $UBR) > ubrnum.$SSTRING
echo 11 > ubrnum.clear.$SSTRING
}
ubr12() {
(echo "$ubruser";echo "$ubrpass" ; echo "$searchstring" ;echo exit) | nc -n $ubr12ip 23 | grep -v ">" | grep -v ÿ | grep -v User | grep -v Pass  | grep -v "+"  > ubr-info.$SSTRING
(echo $UBR) > ubrnum.$SSTRING
echo 12 > ubrnum.clear.$SSTRING
}
ubr13() {
(echo "$ubruser";echo "$ubrpass" ; echo "$searchstring" ;echo exit) | nc -n $ubr13ip 23 | grep -v ">" | grep -v ÿ | grep -v User | grep -v Pass  | grep -v "+" > ubr-info.$SSTRING
(echo $UBR) > ubrnum.$SSTRING
echo 13 > ubrnum.clear.$SSTRING
}
ubr14() {
(echo "$ubruser";echo "$ubrpass" ; echo "$searchstring" ;echo exit) | nc -n $ubr14ip 23 | grep -v ">" | grep -v ÿ | grep -v User | grep -v Pass  | grep -v "+" > ubr-info.$SSTRING
(echo $UBR) > ubrnum.$SSTRING
echo 14 > ubrnum.clear.$SSTRING
}
ubr15() {
(echo "$ubruser";echo "$ubrpass" ; echo "$searchstring" ;echo exit) | nc -n $ubr15ip 23 | grep -v ">" | grep -v ÿ | grep -v User | grep -v Pass  | grep -v "+" > ubr-info.$SSTRING
(echo $UBR) > ubrnum.$SSTRING
echo 15 > ubrnum.clear.$SSTRING
}
ubr16() {
(echo "$ubruser";echo "$ubrpass" ; echo "$searchstring" ;echo exit) | nc -n $ubr16ip 23 | grep -v ">" | grep -v ÿ | grep -v User | grep -v Pass  | grep -v "+" > ubr-info.$SSTRING
(echo $UBR) > ubrnum.$SSTRING
echo 16 > ubrnum.clear.$SSTRING
}
ubr17() {
(echo "$ubruser";echo "$ubrpass" ; echo "$searchstring" ;echo exit) | nc -n $ubr17ip 23 | grep -v ">" | grep -v ÿ | grep -v User | grep -v Pass  | grep -v "+" > ubr-info.$SSTRING
(echo $UBR) > ubrnum.$SSTRING
echo 17 > ubrnum.clear.$SSTRING
}
ubr18() {
(echo "$ubruser";echo "$ubrpass" ; echo "$searchstring" ;echo exit) | nc -n $ubr18ip 23 | grep -v ">" | grep -v ÿ | grep -v User | grep -v Pass  | grep -v "+" > ubr-info.$SSTRING
(echo $UBR) > ubrnum.$SSTRING
echo 18 > ubrnum.clear.$SSTRING
}
ubr19() {
(echo "$ubruser";echo "$ubrpass" ; echo "$searchstring" ;echo exit) | nc -n $ubr19ip 23 | grep -v ">" | grep -v ÿ | grep -v User | grep -v Pass  | grep -v "+" > ubr-info.$SSTRING
(echo $UBR) > ubrnum.$SSTRING
echo 19 > ubrnum.clear.$SSTRING
}
ubr20() {
(echo "$ubruser";echo "$ubrpass" ; echo "$searchstring" ;echo exit) | nc -n $ubr20ip 23 | grep -v ">" | grep -v ÿ | grep -v User | grep -v Pass  | grep -v "+" > ubr-info.$SSTRING
(echo $UBR) > ubrnum.$SSTRING
echo 20 > ubrnum.clear.$SSTRING
}
ubr21() {
(echo "$ubruser";echo "$ubrpass" ; echo "$searchstring" ;echo exit) | nc -n $ubr21ip 23 | grep -v ">" | grep -v ÿ | grep -v User | grep -v Pass  | grep -v "+" > ubr-info.$SSTRING
(echo $UBR) > ubrnum.$SSTRING
echo 21 > ubrnum.clear.$SSTRING
}
ubr22() {
(echo "$ubruser";echo "$ubrpass" ; echo "$searchstring" ;echo exit) | nc -n $ubr22ip 23 | grep -v ">" | grep -v ÿ | grep -v User | grep -v Pass  | grep -v "+"  > ubr-info.$SSTRING
(echo $UBR) > ubrnum.$SSTRING
echo 22 > ubrnum.clear.$SSTRING
}
ubr23() {
(echo "$ubruser";echo "$ubrpass" ; echo "$searchstring" ;echo exit) | nc -n $ubr23ip 23 | grep -v ">" | grep -v ÿ | grep -v User | grep -v Pass  | grep -v "+" > ubr-info.$SSTRING
(echo $UBR) > ubrnum.$SSTRING
echo 23 > ubrnum.clear.$SSTRING
}
ubr24() {
(echo "$ubruser";echo "$ubrpass" ; echo "$searchstring" ;echo exit) | nc -n $ubr24ip 23 | grep -v ">" | grep -v ÿ | grep -v User | grep -v Pass  | grep -v "+" > ubr-info.$SSTRING
(echo $UBR) > ubrnum.$SSTRING
echo 24 > ubrnum.clear.$SSTRING
}
ubr25() {
(echo "$ubruser";echo "$ubrpass" ; echo "$searchstring" ;echo exit) | nc -n $ubr25ip 23 | grep -v ">" | grep -v ÿ | grep -v User | grep -v Pass  | grep -v "+" > ubr-info.$SSTRING
(echo $UBR) > ubrnum.$SSTRING
echo 25 > ubrnum.clear.$SSTRING
}
ubr26() {
(echo "$ubruser";echo "$ubrpass" ; echo "$searchstring" ;echo exit) | nc -n $ubr26ip 23 | grep -v ">" | grep -v ÿ | grep -v User | grep -v Pass  | grep -v "+" > ubr-info.$SSTRING
(echo $UBR) > ubrnum.$SSTRING
echo 26 > ubrnum.clear.$SSTRING
}
ubr27() {
(echo "$ubruser";echo "$ubrpass" ; echo "$searchstring" ;echo exit) | nc -n $ubr27ip 23 | grep -v ">" | grep -v ÿ | grep -v User | grep -v Pass  | grep -v "+" > ubr-info.$SSTRING
(echo $UBR) > ubrnum.$SSTRING
echo 27 > ubrnum.clear.$SSTRING
}
ubr28() {
(echo "$ubruser";echo "$ubrpass" ; echo "$searchstring" ;echo exit) | nc -n $ubr28ip 23 | grep -v ">" | grep -v ÿ | grep -v User | grep -v Pass  | grep -v "+" > ubr-info.$SSTRING
(echo $UBR) > ubrnum.$SSTRING
echo 28 > ubrnum.clear.$SSTRING
}
ubr29() {
(echo "$ubruser";echo "$ubrpass" ; echo "$searchstring" ;echo exit) | nc -n $ubr29ip 23 | grep -v ">" | grep -v ÿ | grep -v User | grep -v Pass  | grep -v "+" > ubr-info.$SSTRING
(echo $UBR) > ubrnum.$SSTRING
echo 29 > ubrnum.clear.$SSTRING
}
ubr30() {
(echo "$ubruser";echo "$ubrpass" ; echo "$searchstring" ;echo exit) | nc -n $ubr30ip 23 | grep -v ">" | grep -v ÿ | grep -v User | grep -v Pass  | grep -v "+" > ubr-info.$SSTRING
(echo $UBR) > ubrnum.$SSTRING
echo 30 > ubrnum.clear.$SSTRING
}
ubr31() {
(echo "$ubruser";echo "$ubrpass" ; echo "$searchstring" ;echo exit) | nc -n $ubr31ip 23 | grep -v ">" | grep -v ÿ | grep -v User | grep -v Pass  | grep -v "+" > ubr-info.$SSTRING
(echo $UBR) > ubrnum.$SSTRING
echo 31 > ubrnum.clear.$SSTRING
}
ubr32() {
(echo "$ubruser";echo "$ubrpass" ; echo "$searchstring" ;echo exit) | nc -n $ubr32ip 23 | grep -v ">" | grep -v ÿ | grep -v User | grep -v Pass  | grep -v "+"  > ubr-info.$SSTRING
(echo $UBR) > ubrnum.$SSTRING
echo 32 > ubrnum.clear.$SSTRING
}
ubr33() {
(echo "$ubruser";echo "$ubrpass" ; echo "$searchstring" ;echo exit) | nc -n $ubr33ip 23 | grep -v ">" | grep -v ÿ | grep -v User | grep -v Pass  | grep -v "+" > ubr-info.$SSTRING
(echo $UBR) > ubrnum.$SSTRING
echo 33 > ubrnum.clear.$SSTRING
}
ubr34() {
(echo "$ubruser";echo "$ubrpass" ; echo "$searchstring" ;echo exit) | nc -n $ubr34ip 23 | grep -v ">" | grep -v ÿ | grep -v User | grep -v Pass  | grep -v "+" > ubr-info.$SSTRING
(echo $UBR) > ubrnum.$SSTRING
echo 34 > ubrnum.clear.$SSTRING
}
ubr35() {
(echo "$ubruser";echo "$ubrpass" ; echo "$searchstring" ;echo exit) | nc -n $ubr35ip 23 | grep -v ">" | grep -v ÿ | grep -v User | grep -v Pass  | grep -v "+" > ubr-info.$SSTRING
(echo $UBR) > ubrnum.$SSTRING
echo 35 > ubrnum.clear.$SSTRING
}
ubr36() {
(echo "$ubruser";echo "$ubrpass" ; echo "$searchstring" ;echo exit) | nc -n $ubr36ip 23 | grep -v ">" | grep -v ÿ | grep -v User | grep -v Pass  | grep -v "+" > ubr-info.$SSTRING
(echo $UBR) > ubrnum.$SSTRING
echo 36 > ubrnum.clear.$SSTRING
}
ubr37() {
(echo "$ubruser";echo "$ubrpass" ; echo "$searchstring" ;echo exit) | nc -n $ubr37ip 23 | grep -v ">" | grep -v ÿ | grep -v User | grep -v Pass  | grep -v "+" > ubr-info.$SSTRING
(echo $UBR) > ubrnum.$SSTRING
echo 37 > ubrnum.clear.$SSTRING
}
ubr38() {
(echo "$ubruser";echo "$ubrpass" ; echo "$searchstring" ;echo exit) | nc -n $ubr38ip 23 | grep -v ">" | grep -v ÿ | grep -v User | grep -v Pass  | grep -v "+" > ubr-info.$SSTRING
(echo $UBR) > ubrnum.$SSTRING
echo 38 > ubrnum.clear.$SSTRING
}
ubr39() {
(echo "$ubruser";echo "$ubrpass" ; echo "$searchstring" ;echo exit) | nc -n $ubr39ip 23 | grep -v ">" | grep -v ÿ | grep -v User | grep -v Pass  | grep -v "+" > ubr-info.$SSTRING
(echo $UBR) > ubrnum.$SSTRING
echo 39 > ubrnum.clear.$SSTRING
}
ubr40() {
(echo "$ubruser";echo "$ubrpass" ; echo "$searchstring" ;echo exit) | nc -n $ubr40ip 23 | grep -v ">" | grep -v ÿ | grep -v User | grep -v Pass  | grep -v "+" > ubr-info.$SSTRING
(echo $UBR) > ubrnum.$SSTRING
echo 40 > ubrnum.clear.$SSTRING
}
ubr41() {
(echo "$ubruser";echo "$ubrpass" ; echo "$searchstring" ;echo exit) | nc -n $ubr41ip 23 | grep -v ">" | grep -v ÿ | grep -v User | grep -v Pass  | grep -v "+" > ubr-info.$SSTRING
(echo $UBR) > ubrnum.$SSTRING
echo 41 > ubrnum.clear.$SSTRING
}
ubr42() {
(echo "$ubruser";echo "$ubrpass" ; echo "$searchstring" ;echo exit) | nc -n $ubr42ip 23 | grep -v ">" | grep -v ÿ | grep -v User | grep -v Pass  | grep -v "+"  > ubr-info.$SSTRING
(echo $UBR) > ubrnum.$SSTRING
echo 42 > ubrnum.clear.$SSTRING
}
ubr43() {
(echo "$ubruser";echo "$ubrpass" ; echo "$searchstring" ;echo exit) | nc -n $ubr43ip 23 | grep -v ">" | grep -v ÿ | grep -v User | grep -v Pass  | grep -v "+" > ubr-info.$SSTRING
(echo $UBR) > ubrnum.$SSTRING
echo 43 > ubrnum.clear.$SSTRING
}
ubr44() {
(echo "$ubruser";echo "$ubrpass" ; echo "$searchstring" ;echo exit) | nc -n $ubr44ip 23 | grep -v ">" | grep -v ÿ | grep -v User | grep -v Pass  | grep -v "+" > ubr-info.$SSTRING
(echo $UBR) > ubrnum.$SSTRING
echo 44 > ubrnum.clear.$SSTRING
}
ubr45() {
(echo "$ubruser";echo "$ubrpass" ; echo "$searchstring" ;echo exit) | nc -n $ubr45ip 23 | grep -v ">" | grep -v ÿ | grep -v User | grep -v Pass  | grep -v "+" > ubr-info.$SSTRING
(echo $UBR) > ubrnum.$SSTRING
echo 45 > ubrnum.clear.$SSTRING
}
ubr46() {
(echo "$ubruser";echo "$ubrpass" ; echo "$searchstring" ;echo exit) | nc -n $ubr46ip 23 | grep -v ">" | grep -v ÿ | grep -v User | grep -v Pass  | grep -v "+" > ubr-info.$SSTRING
(echo $UBR) > ubrnum.$SSTRING
echo 46 > ubrnum.clear.$SSTRING
}
ubr47() {
(echo "$ubruser";echo "$ubrpass" ; echo "$searchstring" ;echo exit) | nc -n $ubr47ip 23 | grep -v ">" | grep -v ÿ | grep -v User | grep -v Pass  | grep -v "+" > ubr-info.$SSTRING
(echo $UBR) > ubrnum.$SSTRING
echo 47 > ubrnum.clear.$SSTRING
}
ubr48() {
(echo "$ubruser";echo "$ubrpass" ; echo "$searchstring" ;echo exit) | nc -n $ubr48ip 23 | grep -v ">" | grep -v ÿ | grep -v User | grep -v Pass  | grep -v "+" > ubr-info.$SSTRING
(echo $UBR) > ubrnum.$SSTRING
echo 48 > ubrnum.clear.$SSTRING
}
ubr49() {
(echo "$ubruser";echo "$ubrpass" ; echo "$searchstring" ;echo exit) | nc -n $ubr49ip 23 | grep -v ">" | grep -v ÿ | grep -v User | grep -v Pass  | grep -v "+" > ubr-info.$SSTRING
(echo $UBR) > ubrnum.$SSTRING
echo 49 > ubrnum.clear.$SSTRING
}
ubr50() {
(echo "$ubruser";echo "$ubrpass" ; echo "$searchstring" ;echo exit) | nc -n $ubr50ip 23 | grep -v ">" | grep -v ÿ | grep -v User | grep -v Pass  | grep -v "+" > ubr-info.$SSTRING
(echo $UBR) > ubrnum.$SSTRING
echo 50 > ubrnum.clear.$SSTRING
}

# determine what ubr number was passed, make the variable $UBR equal
# the name of the uBR sub it's about to launch (for use in the cmsearch script)
case "$1" in
  1)
    UBR=$ubr1name
    ubr1
    ;;
  2)
    UBR=$ubr2name
    ubr2
    ;;
  3)
    UBR=$ubr3name
    ubr3
    ;;
  4)
    UBR=$ubr4name
    ubr4
    ;;
  5)
    UBR=$ubr5name
    ubr5
    ;;
  6)
    UBR=$ubr6name
    ubr6
    ;;
  7)
    UBR=$ubr7name
    ubr7
    ;;
  8)
    UBR=$ubr8name
    ubr8
    ;;
  9)
    UBR=$ubr9name
    ubr9
    ;;
 10)
    UBR=$ubr10name
    ubr10
    ;;
 11)
    UBR=$ubr11name
    ubr11
    ;;
 12)
    UBR=$ubr12name
    ubr12
    ;;
 13)
    UBR=$ubr13name
    ubr13
    ;;
 14)
    UBR=$ubr14name
    ubr14
    ;;
 15)
    UBR=$ubr15name
    ubr15
    ;;
 16)
    UBR=$ubr16name
    ubr16
    ;;
 17)
    UBR=$ubr17name
    ubr17
    ;;
 18)
    UBR=$ubr18name
    ubr18
    ;;
 19)
    UBR=$ubr19name
    ubr19
    ;;
 20)
    UBR=$ubr20name
    ubr20
    ;;
 21)
    UBR=$ubr21name
    ubr21
    ;;
 22)
    UBR=$ubr22name
    ubr22
    ;;
 23)
    UBR=$ubr23name
    ubr23
    ;;
 24)
    UBR=$ubr24name
    ubr24
    ;;
 25)
    UBR=$ubr25name
    ubr25
    ;;
 26)
    UBR=$ubr26name
    ubr26
    ;;
 27)
    UBR=$ubr27name
    ubr27
    ;;
 28)
    UBR=$ubr28name
    ubr28
    ;;
 29)
    UBR=$ubr29name
    ubr29
    ;;
 30)
    UBR=$ubr30name
    ubr30
    ;;
 31)
    UBR=$ubr31name
    ubr31
    ;;
 32)
    UBR=$ubr32name
    ubr32
    ;;
 33)
    UBR=$ubr33name
    ubr33
    ;;
 34)
    UBR=$ubr34name
    ubr34
    ;;
 35)
    UBR=$ubr35name
    ubr35
    ;;
 36)
    UBR=$ubr36name
    ubr36
    ;;
 37)
    UBR=$ubr37name
    ubr37
    ;;
 38)
    UBR=$ubr38name
    ubr38
    ;;
 39)
    UBR=$ubr39name
    ubr39
    ;;
 40)
    UBR=$ubr40name
    ubr40
    ;;
 41)
    UBR=$ubr41name
    ubr41
    ;;
 42)
    UBR=$ubr42name
    ubr42
    ;;
 43)
    UBR=$ubr43name
    ubr43
    ;;
 44)
    UBR=$ubr44name
    ubr44
    ;;
 45)
    UBR=$ubr45name
    ubr45
    ;;
 46)
    UBR=$ubr46name
    ubr46
    ;;
 47)
    UBR=$ubr47name
    ubr47
    ;;
 48)
    UBR=$ubr48name
    ubr48
    ;;
 49)
    UBR=$ubr49name
    ubr49
    ;;
 50)
    UBR=$ubr50name
    ubr50
    ;;
esac